### PR TITLE
Add option to custom header

### PR DESCRIPTION
**Pull request by mflm30**
Hi,

Due to the need to define a variable in the request, I added to the form the possibility of having a header with a key and value.

Tested on a local instance with a custom headerwith success.

Thanks.

### CODE REVIEW

**Comment by mflm30** [comment]
Hi,

@julienduchesne @dblanchette, 

You can return feedback on that PR.

Thanks.

**Comment by dblanchette** [comment]
Thanks for this PR!

There seems to be many changes related to releasing. Would you mind explaining them?

As for the change itself, it looks good, but it would be better if we had the option to specify multiple headers, not just one.

**Comment by me42th** [comment]
@dblanchette this feature is very importante to my team, can u aprove it please? Thanks a lot : D

**Comment by lemosdeveloper** [comment]
this would help a LOT, both my team and my personal projects.

**Comment by ragnadm** [comment]
"me gusta" this feature, thks for this PR!

**Comment by dnmag** [comment]
Thks for this PR, but can you release this feature pls? I need it so much, would help me and my team a lot!! @dblanchette

**Pull request merged**
